name: Python CI
# This workflow will install Python dependencies and run tests using pytest
# It is triggered on pushes and pull requests to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# step2 Setup environment
# Define the jobs that will run in this workflow
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    # step3 Install dependencies and run tests
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
   # step4 Run tests
    - name: Test with pytest
      run: |
        pytest
